name: Go Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Initialize Go module
      run: |
        cd ${{ github.workspace }}
        go mod init github.com/ilovend/clash
        go mod download github.com/Yawning/chacha20
        go mod tidy


    - name: Build
      run: go build -v ./...
